### ISSUE TITLE
tests come with lab, yet lab is written as if you should be writing the tests along the way

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/angular-testing-custom-filters-readme#2]

**Comment by aturkewi** [comment]
@ipc103 This looks like it should be a readme. Is it alright if I toggle it?

@PeterBell

**Comment by PeterBell** [comment]
Hey @aturkewi I'm cool with that. Feels like we should make it more lab like sometime, but for now, readme would be fine!

**Comment by aturkewi** [comment]
All set. Toggled to a ReadMe
